// Automatically generated by flapigen
package org.iota.client;

/**
 * Builder of GET /api/v1/address/{address} endpoint
 */
public final class GetAddressBuilder {

    private GetAddressBuilder() {}
    /**
     * Consume the builder and get the balance of a given Bech32 encoded address.
     * If count equals maxResults, then there might be more outputs available but those were skipped for performance
     * reasons. User should sweep the address to reduce the amount of outputs.
     * @param address The address to get the balance for
     */
    public final BalanceAddressResponse balance(String address) {
        long ret = do_balance(mNativeObj, address);
        BalanceAddressResponse convRet = new BalanceAddressResponse(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_balance(long self, String address);
    /**
     * Consume the builder and get all outputs that use a given address.
     * If count equals maxResults, then there might be more outputs available but those were skipped for performance
     * reasons. User should sweep the address to reduce the amount of outputs.
     * @param address The address to get the balance for
     * @param options The options for finding outputs
     */
    public final UtxoInput [] outputs(String address, OutputsOptions options) {
        long a1 = options.mNativeObj;
        options.mNativeObj = 0;

        UtxoInput [] ret = do_outputs(mNativeObj, address, a1);
        java.lang.ref.Reference.reachabilityFence(options);

        return ret;
    }
    private static native UtxoInput [] do_outputs(long self, String address, long options);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ GetAddressBuilder(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}