// Automatically generated by flapigen
package org.iota.client;


public final class GossipDto {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private GossipDto() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * The hearthbeat information
     */
    public final HeartbeatDto heartbeat() {
        long ret = do_heartbeat(mNativeObj);
        HeartbeatDto convRet = new HeartbeatDto(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_heartbeat(long self);
    /**
     * The metrics information
     */
    public final MetricsDto metrics() {
        long ret = do_metrics(mNativeObj);
        MetricsDto convRet = new MetricsDto(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_metrics(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ GossipDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}