// Automatically generated by flapigen
package org.iota.client;


public final class IndexPublicDto {

    private IndexPublicDto() {}

    public final long index() {
        long ret = do_index(mNativeObj);

        return ret;
    }
    private static native long do_index(long self);

    public final boolean isPublic() {
        boolean ret = do_isPublic(mNativeObj);

        return ret;
    }
    private static native boolean do_isPublic(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ IndexPublicDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}