// Automatically generated by flapigen
package org.iota.client;


public final class IndexationPayload {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private IndexationPayload() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Serializes the indexation payload into a json string
     */
    public final String serialize() {
        String ret = do_serialize(mNativeObj);

        return ret;
    }
    private static native String do_serialize(long self);
    /**
     * Turns a serialized indexation payload string back into its class
     */
    public static IndexationPayload deserialize(String serialised_data) {
        long ret = do_deserialize(serialised_data);
        IndexationPayload convRet = new IndexationPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_deserialize(String serialised_data);
    /**
     * Creates a new `IndexationPayload`.
     * @param index The index
     * @param data The data linked ot this index
     */
    public static IndexationPayload fromBytes(byte [] index, byte [] data) {
        long ret = do_fromBytes(index, data);
        IndexationPayload convRet = new IndexationPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_fromBytes(byte [] index, byte [] data);
    /**
     * Creates a new `IndexationPayload` from strings
     * @param index The index
     * @param data The data linked ot this index
     */
    public static IndexationPayload fromStrings(String index, String data) {
        long ret = do_fromStrings(index, data);
        IndexationPayload convRet = new IndexationPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_fromStrings(String index, String data);
    /**
     * Returns the index of an `IndexationPayload`.
     */
    public final byte [] index() {
        byte [] ret = do_index(mNativeObj);

        return ret;
    }
    private static native byte [] do_index(long self);

    public final String indexString() {
        String ret = do_indexString(mNativeObj);

        return ret;
    }
    private static native String do_indexString(long self);
    /**
     * Returns the data of an `IndexationPayload`.
     */
    public final byte [] data() {
        byte [] ret = do_data(mNativeObj);

        return ret;
    }
    private static native byte [] do_data(long self);

    public final String dataString() {
        String ret = do_dataString(mNativeObj);

        return ret;
    }
    private static native String do_dataString(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ IndexationPayload(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}