// Automatically generated by flapigen
package org.iota.client;


public final class Input {
    @Override
    public String toString() {{
        return this.to_string();
    }}

    public boolean equals(Object obj) {
        boolean equal = false;
        if (obj instanceof Input)
        equal = ((Input)obj).rustEq(this);
        return equal;
    }

    public int hashCode() {
        return (int)mNativeObj;
    }


    private Input() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    private final boolean rustEq(Input o) {
        long a0 = o.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);
        java.lang.ref.Reference.reachabilityFence(o);

        return ret;
    }
    private static native boolean do_rustEq(long self, long o);

    public final InputKind kind() {
        int ret = do_kind(mNativeObj);
        InputKind convRet = InputKind.fromInt(ret);

        return convRet;
    }
    private static native int do_kind(long self);

    public final UtxoInput asUtxo() {
        long ret = do_asUtxo(mNativeObj);
        UtxoInput convRet = new UtxoInput(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asUtxo(long self);

    public final TreasuryInput asTreasury() {
        long ret = do_asTreasury(mNativeObj);
        TreasuryInput convRet = new TreasuryInput(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asTreasury(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Input(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}