// Automatically generated by flapigen
package org.iota.client;


public enum LedgerInclusionStateDto {
    CONFLICTING(0),
    INCLUDED(1),
    NO_TRANSACTION(2);

    private final int value;
    LedgerInclusionStateDto(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static LedgerInclusionStateDto fromInt(int x) {
        switch (x) {
            case 0: return CONFLICTING;
            case 1: return INCLUDED;
            case 2: return NO_TRANSACTION;
            default: throw new Error("Invalid value for enum LedgerInclusionStateDto: " + x);
        }
    }
}
