// Automatically generated by flapigen
package org.iota.client;

/**
 * Represent the object that nodes gossip around the network.
 */
public final class Message {
    public boolean equals(Object obj) {
        boolean equal = false;
        if (obj instanceof Message)
        equal = ((Message)obj).rustEq(this);
        return equal;
    }

    public int hashCode() {
        return (int)mNativeObj;
    }

    @Override
    public String toString() {{
        return this.to_string();
    }}


    private Message() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    private final boolean rustEq(Message o) {
        long a0 = o.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);
        java.lang.ref.Reference.reachabilityFence(o);

        return ret;
    }
    private static native boolean do_rustEq(long self, long o);
    /**
     * Serializes the receipt payload into a json string
     */
    public final String serialize() {
        String ret = do_serialize(mNativeObj);

        return ret;
    }
    private static native String do_serialize(long self);
    /**
     * Turns a serialized receipt payload string back into its class
     */
    public static Message deserialize(String serialised_data) {
        long ret = do_deserialize(serialised_data);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_deserialize(String serialised_data);
    /**
     * Creates a new `MessageBuilder` to construct an instance of a `Message`.
     */
    public static MessageBuilder builder() {
        long ret = do_builder();
        MessageBuilder convRet = new MessageBuilder(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_builder();
    /**
     * Returns the network id of a `Message`.
     */
    public final long networkId() {
        long ret = do_networkId(mNativeObj);

        return ret;
    }
    private static native long do_networkId(long self);
    /**
     * Computes the identifier of the message.
     */
    public final MessageId id() {
        long ret = do_id(mNativeObj);
        MessageId convRet = new MessageId(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_id(long self);
    /**
     * Returns the nonce of a `Message`.
     */
    public final long nonce() {
        long ret = do_nonce(mNativeObj);

        return ret;
    }
    private static native long do_nonce(long self);
    /**
     * Returns the parents of a `Message`.
     */
    public final MessageId [] parents() {
        MessageId [] ret = do_parents(mNativeObj);

        return ret;
    }
    private static native MessageId [] do_parents(long self);
    /**
     * Returns the optional payload of a `Message`.
     */
    public final java.util.Optional<MessagePayload> payload() {
        long ret = do_payload(mNativeObj);
        java.util.Optional<MessagePayload> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new MessagePayload(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_payload(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Message(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}