// Automatically generated by flapigen
package org.iota.client;

/**
 * Message payload wrapper
 */
public final class MessagePayload {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private MessagePayload() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Turns a serialized message payload string back into its class
     */
    public static MessagePayload deserialize(String serialised_data) {
        long ret = do_deserialize(serialised_data);
        MessagePayload convRet = new MessagePayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_deserialize(String serialised_data);
    /**
     * Get the type of message this contains (used to select the correct getter)
     */
    public final MessagePayloadType payloadType() {
        int ret = do_payloadType(mNativeObj);
        MessagePayloadType convRet = MessagePayloadType.fromInt(ret);

        return convRet;
    }
    private static native int do_payloadType(long self);

    public final IndexationPayload asIndexation() {
        long ret = do_asIndexation(mNativeObj);
        IndexationPayload convRet = new IndexationPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asIndexation(long self);

    public final MilestonePayload asMilestone() {
        long ret = do_asMilestone(mNativeObj);
        MilestonePayload convRet = new MilestonePayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asMilestone(long self);

    public final TransactionPayload asTransaction() {
        long ret = do_asTransaction(mNativeObj);
        TransactionPayload convRet = new TransactionPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asTransaction(long self);

    public final ReceiptPayload asReceipt() {
        long ret = do_asReceipt(mNativeObj);
        ReceiptPayload convRet = new ReceiptPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asReceipt(long self);

    public final TreasuryPayload asTreasury() {
        long ret = do_asTreasury(mNativeObj);
        TreasuryPayload convRet = new TreasuryPayload(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_asTreasury(long self);
    /**
     * Serializes the message payload into a json string
     */
    public final String serialize() {
        String ret = do_serialize(mNativeObj);

        return ret;
    }
    private static native String do_serialize(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MessagePayload(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}