// Automatically generated by flapigen
package org.iota.client;


public final class MigratedFundsEntry {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private MigratedFundsEntry() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Creates a new `MigratedFundsEntry`.
     * @param hash The hash from the transaction used to receive the funds
     * @param output the output related to this transaction
     */
    public static MigratedFundsEntry from(String hash, SignatureLockedSingleOutput output) {
        long a1 = output.mNativeObj;
        output.mNativeObj = 0;

        long ret = do_from(hash, a1);
        MigratedFundsEntry convRet = new MigratedFundsEntry(InternalPointerMarker.RAW_PTR, ret);
        java.lang.ref.Reference.reachabilityFence(output);

        return convRet;
    }
    private static native long do_from(String hash, long output);
    /**
     * Returns the tail transaction hash of a `MigratedFundsEntry`.
     */
    public final String tailTransactionHash() {
        String ret = do_tailTransactionHash(mNativeObj);

        return ret;
    }
    private static native String do_tailTransactionHash(long self);
    /**
     * Returns the output of a `MigratedFundsEntry`.
     */
    public final SignatureLockedSingleOutput output() {
        long ret = do_output(mNativeObj);
        SignatureLockedSingleOutput convRet = new SignatureLockedSingleOutput(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_output(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MigratedFundsEntry(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}