// Automatically generated by flapigen
package org.iota.client;


public final class MilestoneSignature {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private MilestoneSignature() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Gets the signature of the milestone
     */
    public final byte [] getSignature() {
        byte [] ret = do_getSignature(mNativeObj);

        return ret;
    }
    private static native byte [] do_getSignature(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MilestoneSignature(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}