// Automatically generated by flapigen
package org.iota.client;


public final class MilestoneResponse {
    @Override
    public String toString() {{
        return this.to_string();
    }}

    public boolean equals(Object obj) {
        boolean equal = false;
        if (obj instanceof MilestoneResponse)
        equal = ((MilestoneResponse)obj).rustEq(this);
        return equal;
    }

    public int hashCode() {
        return (int)mNativeObj;
    }


    private MilestoneResponse() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    private final boolean rustEq(MilestoneResponse o) {
        long a0 = o.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(o);

        return ret;
    }
    private static native boolean do_rustEq(long self, long o);
    /**
     * Milestone index.
     */
    public final long index() {
        long ret = do_index(mNativeObj);

        return ret;
    }
    private static native long do_index(long self);
    /**
     * Milestone message id
     */
    public final MessageId messageId() {
        long ret = do_messageId(mNativeObj);
        MessageId convRet = new MessageId(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_messageId(long self);
    /**
     * Milestone timestamp.
     */
    public final long timestamp() {
        long ret = do_timestamp(mNativeObj);

        return ret;
    }
    private static native long do_timestamp(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MilestoneResponse(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}