// Automatically generated by flapigen
package org.iota.client;


public enum MqttEvent {
        /**
     * Client was connected.
     */
    CONNECTED(0),
        /**
     * Client was disconnected.
     */
    DISCONNECTED(1);

    private final int value;
    MqttEvent(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static MqttEvent fromInt(int x) {
        switch (x) {
            case 0: return CONNECTED;
            case 1: return DISCONNECTED;
            default: throw new Error("Invalid value for enum MqttEvent: " + x);
        }
    }
}
