// Automatically generated by flapigen
package org.iota.client;

/**
 * Wrapper for node information
 */
public final class NodeInfoWrapper {
    @Override
    public String toString() {{
        return this.to_string();
    }}

    public boolean equals(Object obj) {
        boolean equal = false;
        if (obj instanceof NodeInfoWrapper)
        equal = ((NodeInfoWrapper)obj).rustEq(this);
        return equal;
    }

    public int hashCode() {
        return (int)mNativeObj;
    }


    private NodeInfoWrapper() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    private final boolean rustEq(NodeInfoWrapper o) {
        long a0 = o.mNativeObj;
        boolean ret = do_rustEq(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(o);

        return ret;
    }
    private static native boolean do_rustEq(long self, long o);
    /**
     * Get the URL from which this info is derived
     */
    public final String url() {
        String ret = do_url(mNativeObj);

        return ret;
    }
    private static native String do_url(long self);
    /**
     * Get the information
     */
    public final InfoResponse nodeInfo() {
        long ret = do_nodeInfo(mNativeObj);
        InfoResponse convRet = new InfoResponse(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_nodeInfo(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ NodeInfoWrapper(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}