// Automatically generated by flapigen
package org.iota.client;


public final class PublicKey {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private PublicKey() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Verify the signature and bytes against this public key
     * @param sig The signature to verify
     * @param bytes The bytes to verify
     */
    public final boolean verify(Signature sig, byte [] bytes) {
        long a0 = sig.mNativeObj;
        sig.mNativeObj = 0;

        boolean ret = do_verify(mNativeObj, a0, bytes);
        java.lang.ref.Reference.reachabilityFence(sig);

        return ret;
    }
    private static native boolean do_verify(long self, long sig, byte [] bytes);
    /**
     * Turns ths public key into bytes
     */
    public final byte [] toBytes() {
        byte [] ret = do_toBytes(mNativeObj);

        return ret;
    }
    private static native byte [] do_toBytes(long self);
    /**
     * Attempt to create a public key from the provided bytes
     * @param bytes The bytes to create the key from
     */
    public static PublicKey tryFromBytes(byte [] bytes) {
        long ret = do_tryFromBytes(bytes);
        PublicKey convRet = new PublicKey(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_tryFromBytes(byte [] bytes);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ PublicKey(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}