// Automatically generated by flapigen
package org.iota.client;


public final class ReceiptPayloadDto {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private ReceiptPayloadDto() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * The type of receipt
     */
    public final long kind() {
        long ret = do_kind(mNativeObj);

        return ret;
    }
    private static native long do_kind(long self);
    /**
     * The milestone index at which the funds of a `ReceiptPayload` were migrated
     */
    public final long migratedAt() {
        long ret = do_migratedAt(mNativeObj);

        return ret;
    }
    private static native long do_migratedAt(long self);
    /**
     * The funds which are migrated
     */
    public final MigratedFundsEntryDto [] funds() {
        MigratedFundsEntryDto [] ret = do_funds(mNativeObj);

        return ret;
    }
    private static native MigratedFundsEntryDto [] do_funds(long self);
    /**
     * Whether a `ReceiptPayload` is the final one for a given migrated at index.
     */
    public final boolean last() {
        boolean ret = do_last(mNativeObj);

        return ret;
    }
    private static native boolean do_last(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ReceiptPayloadDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}