// Automatically generated by flapigen
package org.iota.client;


public final class ReferenceUnlock {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private ReferenceUnlock() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Creates a new `ReferenceUnlock`.
     * @param index The unlock block index we use for signature
     */
    public static ReferenceUnlock from(int index) {
        long ret = do_from(index);
        ReferenceUnlock convRet = new ReferenceUnlock(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_from(int index);
    /**
     * Return the index of a `ReferenceUnlock`.
     */
    public final int index() {
        int ret = do_index(mNativeObj);

        return ret;
    }
    private static native int do_index(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ReferenceUnlock(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}