// Automatically generated by flapigen
package org.iota.client;


public final class RegularEssence {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private RegularEssence() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Gets the transaction inputs.
     */
    public final Input [] inputs() {
        Input [] ret = do_inputs(mNativeObj);

        return ret;
    }
    private static native Input [] do_inputs(long self);
    /**
     * Gets the transaction outputs.
     */
    public final Output [] outputs() {
        Output [] ret = do_outputs(mNativeObj);

        return ret;
    }
    private static native Output [] do_outputs(long self);

    public final java.util.Optional<MessagePayload> payload() {
        long ret = do_payload(mNativeObj);
        java.util.Optional<MessagePayload> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new MessagePayload(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_payload(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ RegularEssence(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}