// Automatically generated by flapigen
package org.iota.client;


public enum Relation {
    KNOWN(0),
    UNKNOWN(1),
    AUTOPEERED(2);

    private final int value;
    Relation(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Relation fromInt(int x) {
        switch (x) {
            case 0: return KNOWN;
            case 1: return UNKNOWN;
            case 2: return AUTOPEERED;
            default: throw new Error("Invalid value for enum Relation: " + x);
        }
    }
}
