// Automatically generated by flapigen
package org.iota.client;


public final class RustHex {

    public static native String encode(String a0);

    public static native String encode(byte [] a0);

    public static native byte [] decode(String s);

    public static native byte [] decode(byte [] s);

    private RustHex() {}
}