// Automatically generated by flapigen
package org.iota.client;


public final class SecretKey {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private SecretKey() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Generate a new secret key
     */
    public static SecretKey generate() {
        long ret = do_generate();
        SecretKey convRet = new SecretKey(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_generate();
    /**
     * Create a new secret key from the bytes
     * @param bytes The bytes to create the key from
     */
    public static SecretKey fromBytes(byte [] bytes) {
        long ret = do_fromBytes(bytes);
        SecretKey convRet = new SecretKey(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_fromBytes(byte [] bytes);
    /**
     * Derive a public key from the secret key
     */
    public final PublicKey publicKey() {
        long ret = do_publicKey(mNativeObj);
        PublicKey convRet = new PublicKey(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_publicKey(long self);
    /**
     * Turn this Secret key into bytes
     */
    public final byte [] toBytes() {
        byte [] ret = do_toBytes(mNativeObj);

        return ret;
    }
    private static native byte [] do_toBytes(long self);
    /**
     * Sign the bytes using this key
     * @param bytes the Bytes to sign
     */
    public final Signature sign(byte [] bytes) {
        long ret = do_sign(mNativeObj, bytes);
        Signature convRet = new Signature(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_sign(long self, byte [] bytes);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SecretKey(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}