// Automatically generated by flapigen
package org.iota.client;


public final class SignatureUnlock {
    @Override
    public String toString() {{
        return this.to_string();
    }}

    /**
     * Create a new Signature inlock block
     * @param public_key The public ket used for this signature block
     * @param signature The signature created for this unlock block
     */
    public SignatureUnlock(byte [] public_key, byte [] signature) {
        mNativeObj = init(public_key, signature);
    }
    private static native long init(byte [] public_key, byte [] signature);

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SignatureUnlock(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}