// Automatically generated by flapigen
package org.iota.client;

/**
 * Output type for deposits that enables an address to receive dust outputs. It can be consumed as an input like a
 * regular SigLockedSingleOutput.
 */
public final class SignatureLockedDustAllowanceOutputDto {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private SignatureLockedDustAllowanceOutputDto() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Returns the amount of a `SignatureLockedDustAllowanceOutputDto`.
     */
    public final long amount() {
        long ret = do_amount(mNativeObj);

        return ret;
    }
    private static native long do_amount(long self);
    /**
     * Returns the address of a `SignatureLockedDustAllowanceOutputDto`.
     */
    public final AddressDto address() {
        long ret = do_address(mNativeObj);
        AddressDto convRet = new AddressDto(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_address(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SignatureLockedDustAllowanceOutputDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}