// Automatically generated by flapigen
package org.iota.client;

/**
 * Describes a deposit to a single address which is unlocked via a signature.
 */
public final class SignatureLockedSingleOutput {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private SignatureLockedSingleOutput() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Creates a new `SignatureLockedSingleOutput`.
     * @param address The address to set
     * @param amount The amount to set
     */
    public static SignatureLockedSingleOutput from(Address address, long amount) {
        long a0 = address.mNativeObj;
        address.mNativeObj = 0;

        long ret = do_from(a0, amount);
        SignatureLockedSingleOutput convRet = new SignatureLockedSingleOutput(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(address);

        return convRet;
    }
    private static native long do_from(long address, long amount);
    /**
     * Returns the amount of a `SignatureLockedSingleOutput`.
     */
    public final long amount() {
        long ret = do_amount(mNativeObj);

        return ret;
    }
    private static native long do_amount(long self);
    /**
     * Returns the address of a `SignatureLockedSingleOutput`.
     */
    public final Address address() {
        long ret = do_address(mNativeObj);
        Address convRet = new Address(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_address(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ SignatureLockedSingleOutput(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}