// Automatically generated by flapigen
package org.iota.client;


public final class TopicEvent {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private TopicEvent() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * the MQTT topic.
     */
    public final String topic() {
        String ret = do_topic(mNativeObj);

        return ret;
    }
    private static native String do_topic(long self);
    /**
     * The MQTT event payload.
     */
    public final String payload() {
        String ret = do_payload(mNativeObj);

        return ret;
    }
    private static native String do_payload(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TopicEvent(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}