// Automatically generated by flapigen
package org.iota.client;


public final class UnlockBlocks {
    @Override
    public String toString() {{
        return this.to_string();
    }}


    private UnlockBlocks() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public static UnlockBlocks from(UnlockBlock[] unlock_blocks) {
        long ret = do_from(unlock_blocks);
        UnlockBlocks convRet = new UnlockBlocks(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_from(UnlockBlock[] unlock_blocks);
    /**
     * Gets a clone of an `UnlockBlock` from `UnlockBlocks`.
     * Returns the referenced unlock block if the requested unlock block was a reference.
     */
    public final java.util.Optional<UnlockBlock> get(long index) {
        long ret = do_get(mNativeObj, index);
        java.util.Optional<UnlockBlock> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new UnlockBlock(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_get(long self, long index);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ UnlockBlocks(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}