// Automatically generated by flapigen
package org.iota.client;


public final class Util {
    /**
     * Function to consolidate all funds from a range of addresses to the address with the lowest index in that range
     * Returns the address to which the funds got consolidated, if any were available
     */
    public static String consolidateFunds(Client client, String seed, long account_index, long address_range_low, long address_range_high) {
        long a0 = client.mNativeObj;
        client.mNativeObj = 0;

        String ret = do_consolidateFunds(a0, seed, account_index, address_range_low, address_range_high);
        java.lang.ref.Reference.reachabilityFence(client);

        return ret;
    }
    private static native String do_consolidateFunds(long client, String seed, long account_index, long address_range_low, long address_range_high);
    /**
     * Function to find the index and public or internal type of an Bech32 encoded address
     */
    public static IndexPublicDto searchAddress(String seed, String bech32_hrp, long account_index, long range_low, long range_high, Address address) {
        long a5 = address.mNativeObj;
        address.mNativeObj = 0;

        long ret = do_searchAddress(seed, bech32_hrp, account_index, range_low, range_high, a5);
        IndexPublicDto convRet = new IndexPublicDto(InternalPointerMarker.RAW_PTR, ret);
        java.lang.ref.Reference.reachabilityFence(address);

        return convRet;
    }
    private static native long do_searchAddress(String seed, String bech32_hrp, long account_index, long range_low, long range_high, long address);

    private Util() {}
}