# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - uses: docker/setup-buildx-action@v1.6.0
      - name: Start containers
        working-directory: ./test_suite
        run: docker-compose up -d

      - run: sleep 60
        
      - name: Run tests
        run: mvn test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: target/surefire-reports/*.xml
